# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 647)
        Form.setStyleSheet("background-color: rgb(26, 29, 35);\n"
"color: rgb(255, 255, 255);")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setMinimumSize(QtCore.QSize(0, 60))
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.dbButton = QtWidgets.QPushButton(self.frame)
        self.dbButton.setMinimumSize(QtCore.QSize(130, 50))
        self.dbButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.dbButton.setObjectName("dbButton")
        self.verticalLayout.addWidget(self.dbButton)
        self.dashboardButton = QtWidgets.QPushButton(self.frame)
        self.dashboardButton.setMinimumSize(QtCore.QSize(130, 50))
        self.dashboardButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.dashboardButton.setObjectName("dashboardButton")
        self.verticalLayout.addWidget(self.dashboardButton)
        self.hasilButton = QtWidgets.QPushButton(self.frame)
        self.hasilButton.setMinimumSize(QtCore.QSize(130, 50))
        self.hasilButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.hasilButton.setObjectName("hasilButton")
        self.verticalLayout.addWidget(self.hasilButton)
        self.grafikButton = QtWidgets.QPushButton(self.frame)
        self.grafikButton.setMinimumSize(QtCore.QSize(130, 50))
        self.grafikButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.grafikButton.setObjectName("grafikButton")
        self.verticalLayout.addWidget(self.grafikButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dbpage = QtWidgets.QWidget()
        self.dbpage.setObjectName("dbpage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dbpage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.dbpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.dbpage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.textBrowser = QtWidgets.QTextBrowser(self.dbpage)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.stackedWidget.addWidget(self.dbpage)
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboardPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.dashboardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.frame_2 = QtWidgets.QFrame(self.dashboardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputButton = QtWidgets.QPushButton(self.frame_2)
        self.inputButton.setMinimumSize(QtCore.QSize(60, 20))
        self.inputButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.inputButton.setObjectName("inputButton")
        self.horizontalLayout_2.addWidget(self.inputButton)
        self.fileLine = QtWidgets.QLineEdit(self.frame_2)
        self.fileLine.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"color: rgb(62, 62, 62);")
        self.fileLine.setObjectName("fileLine")
        self.horizontalLayout_2.addWidget(self.fileLine)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.runButton = QtWidgets.QPushButton(self.dashboardPage)
        self.runButton.setMinimumSize(QtCore.QSize(0, 20))
        self.runButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.runButton.setObjectName("runButton")
        self.verticalLayout_2.addWidget(self.runButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.dashboardPage)
        self.hasilPage = QtWidgets.QWidget()
        self.hasilPage.setObjectName("hasilPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.hasilPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.hasilPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tableView = QtWidgets.QTableView(self.hasilPage)
        self.tableView.setStyleSheet("color: rgb(255, 255, 255);")
        self.tableView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.saveButton = QtWidgets.QPushButton(self.hasilPage)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.saveButton.setStyleSheet("border-radius:3px;\n"
"background-color: rgb(42, 157, 143);\n"
"color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_3.addWidget(self.saveButton)
        self.stackedWidget.addWidget(self.hasilPage)
        self.grafikPage = QtWidgets.QWidget()
        self.grafikPage.setObjectName("grafikPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grafikPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.grafikPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 60))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.frame_3 = QtWidgets.QFrame(self.grafikPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.posLabel = QtWidgets.QLabel(self.frame_4)
        self.posLabel.setStyleSheet("font: 75 36pt \".AppleSystemUIFont\";\n"
"color: rgb(33, 158, 188);")
        self.posLabel.setObjectName("posLabel")
        self.horizontalLayout_7.addWidget(self.posLabel)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.netLabel = QtWidgets.QLabel(self.frame_6)
        self.netLabel.setStyleSheet("font: 75 36pt \".AppleSystemUIFont\";\n"
"color: rgb(255, 183, 3);")
        self.netLabel.setObjectName("netLabel")
        self.horizontalLayout_5.addWidget(self.netLabel)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.negLabel = QtWidgets.QLabel(self.frame_5)
        self.negLabel.setStyleSheet("font: 75 36pt \".AppleSystemUIFont\";\n"
"color: rgb(230, 54, 73);")
        self.negLabel.setObjectName("negLabel")
        self.horizontalLayout_6.addWidget(self.negLabel)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(self.grafikPage)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("color: rgb(19, 22, 26);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.pieWidget = QtWidgets.QWidget(self.frame_8)
        self.pieWidget.setObjectName("pieWidget")
        self.verticalLayout_5.addWidget(self.pieWidget)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("color: rgb(19, 22, 26);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.barWidget = QtWidgets.QWidget(self.frame_9)
        self.barWidget.setObjectName("barWidget")
        self.verticalLayout_6.addWidget(self.barWidget)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.grafikPage)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stackedWidget)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("background-color: rgb(52, 58, 64);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_8)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SentiApp"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; font-style:italic;\">S</span><span style=\" font-size:36pt; font-style:italic;\">enti</span><span style=\" font-size:36pt; font-weight:600; font-style:italic;\">A</span><span style=\" font-size:36pt; font-style:italic;\">pp</span></p></body></html>"))
        self.dbButton.setText(_translate("Form", "Dashboard"))
        self.dashboardButton.setText(_translate("Form", "Upload Data"))
        self.hasilButton.setText(_translate("Form", "Hasil Analisis"))
        self.grafikButton.setText(_translate("Form", "Grafik Analisis"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Selamat Datang di Aplikasi Sentimen Analisis</span></p><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Berbasis Support Vector Machine</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Tata Cara Penggunaan Sistem</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Upload Data :</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Pada fitur Upload Data, User akan memasukan File data yang akan di Analisis untuk sentimennya.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">user akan memilih file yang akan dimasukan dengan menekan tombol choose file pada menu Upload Data</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Hasil Analisis :</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Pada fitur Hasil Analisis, sistem akan menampilkan output dari data, yang berupa hasil dari proses prediksi pada data latih berdasarkan data uji yang telah di tentukan menggunakan algoritma Support Vector Machine.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Hasil analisis berupa tabel dengan kolom sebagai berikut : index, name, timetweet, isitweet, cleantext, label.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Grafik Sentimen :</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Pada fitur Grafik data, sistem akan menampilkan jumlah tweet yang telah dianalisis, grafik data positif negatif, dan netral.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Fitur grafik digunakan agar user dapat lebih mudah membaca hasil analisis sentimen yang telah digunakan.</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Upload Data</span></p></body></html>"))
        self.inputButton.setText(_translate("Form", "Input"))
        self.runButton.setText(_translate("Form", "Jalankan Program"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Hasil Analisis</span></p></body></html>"))
        self.saveButton.setText(_translate("Form", "Simpan Hasil"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Grafik Analisis</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "Tweet Positif"))
        self.posLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">340</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "Tweet Netral"))
        self.netLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">500</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "Tweet Negatif"))
        self.negLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">160</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">GRAFIK SENTIMEN</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">FREKUENSI PENGGUNA</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">FAKULTAS TEKNIK INFORMATIKA</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

